name: people_maker
description: people_maker use randomuser.me api to generate realistic user profiles, providing easy-to-copy diverse and dynamic data.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.2
  cupertino_icons: ^1.0.5
  dash_flags: ^0.1.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^2.3.2
  mobx: ^2.1.4
  mocktail: ^0.3.0
  path_provider: ^2.0.14
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mobx_codegen: ^2.2.0
#  animated_native_splash: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
#
#animated_native_splash:
#
#  # This package generates native code to customize Flutter's splash
#
#  # jsonFile is the only required parameter.This the file use to setup the animation object.
#  jsonFile: assets/lottie/loading.json