name: people_maker
description: people_maker use randomuser.me api to generate realistic user profiles, providing easy-to-copy diverse and dynamic data.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.2.0

flutter:
  uses-material-design: true
